source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target :EllenGif do
    pod 'AFNetworking', '~>3.0'
    pod 'Masonry', '0.6.1' #autolayout解析
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYWebImage'
    pod 'UMengFeedback'
    pod 'UMengAnalytics'
    pod 'Firebase/AdMob'
    pod 'UzysAssetsPickerController'

end
